import { FicheVierge } from '../../models/fiches-vierges';
export const FICHES_VIERGES: FicheVierge[] = [
  {
    archive: false,
    created: true,
    ref: 'A-001',
    frequence: "Annuel et au fil de l'eau",
    responsable: 'RCCI',
    risque: "Risques liés à la gouvernance et à l'actionnariat",
    theme: 'Organisation de la SGP',
  },
  {
    archive: false,
    created: true,
    ref: 'A-002',
    frequence: 'Annuel',
    responsable: 'RCCI',
    risque: 'Risques liés aux moyens humains de la SGP',
    theme: 'Organisation de la SGP',
  },

  {
    archive: true,
    created: true,
    ref: 'B-38834',
    frequence: 'Annuelle',
    responsable: 'Loma Hand',
    risque: 'Accusantium eius explicabo molestiae ad quos quaerat.',
    theme:
      'Aut voluptas illum.Voluptas quibusdam ipsum eos et quia maiores et iusto asperiores.',
  },

  {
    archive: true,
    created: false,
    ref: 'B-45640',
    frequence: 'Mensuelle',
    responsable: 'Raven Haley',
    risque: 'Aliquid est occaecati natus.',
    theme: 'Recusandae eaque qui sapiente et.',
  },
  {
    archive: true,
    created: false,
    ref: 'B-91166',
    frequence: 'Quotidienne/journalière ',
    responsable: 'Clay Greenholt',
    risque: 'Possimus porro doloremque expedita blanditiis sapiente.',
    theme: 'Beatae ab quaerat iste velit perspiciatis qui iure aut molestiae.',
  },
  {
    archive: true,
    created: true,
    ref: 'B-85543',
    frequence: 'Trimestrielle',
    responsable: 'Olaf Reinger',
    risque: 'Labore consequatur exercitationem est ad.',
    theme: 'Recusandae sit nobis distinctio excepturi autem debitis non omnis vero.',
  },
  {
    archive: false,
    created: true,
    ref: 'B-90785',
    frequence: '',
    responsable: 'Albert Tremblay',
    risque: 'Et qui aut enim aliquam.',
    theme: 'Nam velit distinctio tempore itaque itaque ipsam aut.',
  },
  {
    archive: false,
    created: false,
    ref: 'B-30611',
    frequence: 'Semestrielle',
    responsable: 'Karina Hettinger',
    risque: 'Ut sunt tempora in laboriosam.',
    theme: 'Adipisci quaerat sint et sint rerum corporis numquam eos.',
  },
  {
    archive: true,
    created: false,
    ref: 'B-10432',
    frequence: 'Tous les 12 jours',
    responsable: 'Daren Paucek',
    risque: 'Omnis mollitia fugit.',
    theme: 'Similique sunt illo adipisci ex sed.',
  },
  {
    archive: false,
    created: true,
    ref: 'B-36519',
    frequence: '2 semaines',
    responsable: 'Destiney Parker',
    risque: 'Distinctio adipisci earum veritatis porro vero.',
    theme: 'Adipisci non autem consequatur.',
  },
  {
    archive: false,
    created: true,
    ref: 'B-12206',
    frequence: 'Mensuelle',
    responsable: 'Emely Marks',
    risque: 'Magnam tempora corrupti enim ipsa.',
    theme: 'In et sed error.',
  },
  {
    archive: true,
    created: false,
    ref: 'B-16387',
    frequence: "Annuel et au fil de l'eau",
    responsable: 'Haskell Cormier',
    risque: 'Est quibusdam omnis sequi voluptatem temporibus.',
    theme: 'Ut quia id.',
  },
  {
    archive: false,
    created: false,
    ref: 'B-98302',
    frequence: 'Quotidienne/journalière ',
    responsable: 'Deven Walker',
    risque: 'Vel esse dolor praesentium ad architecto quibusdam.',
    theme: 'Quis voluptate tempore quis similique suscipit.',
  },
  {
    archive: false,
    created: true,
    ref: 'B-39448',
    frequence: 'Quotidienne/journalière ',
    responsable: 'Bradley Hermann',
    risque: 'Provident doloremque quidem soluta ut repellat.',
    theme: 'Non quam fugiat neque officia.',
  },
];
