import { Fiches } from '../../models/fiches';
export const FICHES: Fiches[] = [
  {
    finalisationDate: "Fri Oct 06 2023 07:38:33 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: true,
    ref: 'A-001',
    responsable: 'RCCI',
    risque: "Risques liés à la gouvernance et à l'actionnariat",
    theme: 'Organisation de la SGP',
  },
  {
    finalisationDate: "Thu Sep 21 2023 02:48:21 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: true,
    ref: 'A-002',
    responsable: 'RCCI',
    risque: 'Risques liés aux moyens humains de la SGP',
    theme: 'Organisation de la SGP',
  },

  {
    finalisationDate: "Tue Jul 25 2023 09:11:12 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: true,
    created: true,
    ref: 'B-38834',
    responsable: 'Loma Hand',
    risque: 'Accusantium eius explicabo molestiae ad quos quaerat.',
    theme:
      'Aut voluptas illum.Voluptas quibusdam ipsum eos et quia maiores et iusto asperiores.',
  },

  {
    finalisationDate: "Sun Feb 18 2024 19:54:02 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: true,
    created: false,
    ref: 'B-45640',
    responsable: 'Raven Haley',
    risque: 'Aliquid est occaecati natus.',
    theme: 'Recusandae eaque qui sapiente et.',
  },
  {
    finalisationDate: "Thu Feb 22 2024 13:46:23 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: true,
    created: false,
    ref: 'B-91166',
    responsable: 'Clay Greenholt',
    risque: 'Possimus porro doloremque expedita blanditiis sapiente.',
    theme: 'Beatae ab quaerat iste velit perspiciatis qui iure aut molestiae.',
  },
  {
    finalisationDate: "Wed Jul 26 2023 23:13:51 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: true,
    created: true,
    ref: 'B-85543',
    responsable: 'Olaf Reinger',
    risque: 'Labore consequatur exercitationem est ad.',
    theme: 'Recusandae sit nobis distinctio excepturi autem debitis non omnis vero.',
  },
  {
    finalisationDate: "Fri Aug 11 2023 10:15:22 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: true,
    ref: 'B-90785',
    responsable: 'Albert Tremblay',
    risque: 'Et qui aut enim aliquam.',
    theme: 'Nam velit distinctio tempore itaque itaque ipsam aut.',
  },
  {
    finalisationDate: "Thu Nov 09 2023 07:20:04 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: false,
    ref: 'B-30611',
    responsable: 'Karina Hettinger',
    risque: 'Ut sunt tempora in laboriosam.',
    theme: 'Adipisci quaerat sint et sint rerum corporis numquam eos.',
  },
  {
    finalisationDate: "Mon Oct 09 2023 20:45:24 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: true,
    created: false,
    ref: 'B-10432',
    responsable: 'Daren Paucek',
    risque: 'Omnis mollitia fugit.',
    theme: 'Similique sunt illo adipisci ex sed.',
  },
  {
    finalisationDate: "Thu Mar 07 2024 22:58:32 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: true,
    ref: 'B-36519',
    responsable: 'Destiney Parker',
    risque: 'Distinctio adipisci earum veritatis porro vero.',
    theme: 'Adipisci non autem consequatur.',
  },
  {
    finalisationDate: "Thu Apr 25 2024 09:04:58 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: true,
    ref: 'B-12206',
    responsable: 'Emely Marks',
    risque: 'Magnam tempora corrupti enim ipsa.',
    theme: 'In et sed error.',
  },
  {
    finalisationDate: "Tue Nov 28 2023 09:30:34 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: true,
    created: false,
    ref: 'B-16387',
    responsable: 'Haskell Cormier',
    risque: 'Est quibusdam omnis sequi voluptatem temporibus.',
    theme: 'Ut quia id.',
  },
  {
    finalisationDate: "Wed Jan 10 2024 08:35:41 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: false,
    ref: 'B-98302',
    responsable: 'Deven Walker',
    risque: 'Vel esse dolor praesentium ad architecto quibusdam.',
    theme: 'Quis voluptate tempore quis similique suscipit.',
  },
  {
    finalisationDate: "Wed Sep 27 2023 16:52:41 GMT+0300 (heure normale d’Afrique de l’Est)",
    archive: false,
    created: true,
    ref: 'B-39448',
    responsable: 'Bradley Hermann',
    risque: 'Provident doloremque quidem soluta ut repellat.',
    theme: 'Non quam fugiat neque officia.',
  },
];
