export const PRIVILEGES = [
    { checked: false, name: 'Replanifier le contrôle'},
    { checked: true, name: 'Impedit consequatur quasi veniam corporis ipsum omnis nihil.'},
    { checked: true, name: 'Expedita quidem rerum nostrum qui accusamus.'},
    { checked: true, name: 'In accusamus porro.'},
    { checked: false, name: 'Vero dolor exercitationem.'},
    { checked: true, name: 'Molestiae rerum in quas nulla et.'},
    { checked: false, name: 'Modi excepturi fugiat qui vel deserunt nostrum quae.'},
    { checked: false, name: 'Molestiae tenetur tenetur.'},
    { checked: true, name: 'Quia saepe et aperiam impedit consectetur vel velit aliquam perspiciatis.'},
    { checked: true, name: 'Porro et vel consequatur est consectetur non voluptate qui distinctio.'},
    { checked: false, name: 'A ut in nostrum quibusdam alias minus qui suscipit.'},
    { checked: true, name: 'Sint natus ut assumenda et est.'},
    { checked: false, name: 'Sequi ipsam est ducimus odit magni odio eius inventore.'},
    { checked: true, name: 'Aut nulla quidem eius.'},
    { checked: false, name: 'A cumque doloremque inventore et.'},
    { checked: false, name: 'Cum non qui quos temporibus dolor velit quasi recusandae.'},
    { checked: false, name: 'Dolore quia est perferendis non.'},
    { checked: false, name: 'Odio quam ipsum aliquid eum.'},
    { checked: false, name: 'Ex rerum quis beatae ut deserunt et commodi dolor.'},
    { checked: false, name: 'Perspiciatis beatae consequatur earum dolor sed facilis nam in repellendus.'},
    { checked: false, name: 'Sequi soluta eaque numquam.'},
    { checked: true, name: 'Omnis saepe beatae et vero optio qui consectetur voluptatem necessitatibus.'},
    { checked: true, name: 'Itaque non ratione sit voluptas.'},
    { checked: false, name: 'Eos natus odio aliquid.'},
    { checked: true, name: 'Similique deleniti et cum ad animi voluptate quibusdam ratione.'},
    { checked: false, name: 'Repellendus deserunt a sit rem suscipit neque.'},
    { checked: true, name: 'Aut nobis iure enim.'},
    { checked: true, name: 'Magni saepe maxime.'},
    { checked: true, name: 'Expedita saepe magni vero at qui similique vero qui.'},
    { checked: false, name: 'Quod placeat exercitationem sed eum magni provident libero praesentium.'},
    { checked: false, name: 'Fugiat vitae facere.'},
    { checked: false, name: 'Aut eos perferendis et similique amet.'},
    { checked: true, name: 'Non necessitatibus placeat sit cum.'},
]