export const QUESTIONNAIRES = [
    { name: "Caractéristiques générales du fonds : Classe d’actifs", statut: "not_assigned"},
    { name: "Ullam nesciunt eaque.", statut: "need_update"},
    { name: "Temporibus quasi doloribus voluptas doloremque corporis minus.", statut: "awaiting_approval"},
    { name: "Distinctio voluptas quo provident ut veniam qui quod qui.", statut: "approved"},
    { name: "Saepe voluptatem nostrum debitis id.", statut: "archived"},
    { name: "Ut ea recusandae vero ab quo esse ducimus.", statut: "not_assigned"},
    { name: "Est sit vero dolorem quidem blanditiis.", statut: "not_assigned"},
    { name: "Dolores a et enim et corporis.", statut: "awaiting_approval"},
    { name: "Et nobis qui praesentium inventore quia voluptatem est.", statut: "approved"},
    { name: "Voluptatem repellendus cum eos iusto.", statut: "need_update"},
    { name: "Possimus sapiente accusantium accusamus officiis fugit omnis.", statut: "need_update"},
    { name: "Ut voluptatem ipsum ullam quia illum voluptatibus.", statut: "awaiting_approval"},
    { name: "Molestiae architecto aliquid reprehenderit.", statut: "approved"},
    { name: "Repudiandae fuga aliquam.", statut: "approved"},
    { name: "Et qui harum magnam.", statut: "approved"},
    { name: "Aspernatur mollitia quam minus quae.", statut: "approved"},
    { name: "Ut non reprehenderit quo.", statut: "awaiting_approval"},
    { name: "Quasi officia sed nihil cum ex impedit.", statut: "not_assigned"},
    { name: "Rerum assumenda quibusdam et fugit deserunt esse eum et quaerat.", statut: "need_update"},
]
